### ISSUE TITLE
sqlc.embed fails with LEFT JOIN

### ISSUE THREAD

**Issue by hectorj-thetreep** [sqlc-dev/sqlc#2634] opened 2023-08-18 15:33 UTC
### Version

1.20.0

### What happened?

The generated code

```go
func (q *Queries) GetA(ctx context.Context) (GetARow, error) {
	row := q.db.QueryRowContext(ctx, getA)
	var i GetARow
	err := row.Scan(
		&i.A.ID,
		&i.A.Name,
		&i.B.ID,
		&i.B.AID,
		&i.B.Label,
	)
	return i, err
}
```

will fail when there is no B to join to A, because it did not detect that the whole `i.B` is nullable.

### Relevant log output

```shell
sql: Scan error on column index 2, name "id": converting NULL to int32 is unsupported
```

### Database schema

```sql
CREATE TABLE A (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL
);

CREATE TABLE B (
  id BIGSERIAL PRIMARY KEY,
  a_id BIGINT NOT NULL,
  label text NOT NULL
);
```

### SQL queries

```sql
SELECT sqlc.embed(A), sqlc.embed(B) FROM A LEFT JOIN B ON A.id = B.a_id LIMIT 1;
```

### Playground URL

https://play.sqlc.dev/p/c045f5e33caf61f3e913a742f08518a167c247c4e5902a995f17ee200a553b2a](https://play.sqlc.dev/p/a6840c57f06a38387e9af1604059bb1db09e0db71f7a462c7bcd6a8dcfc42043

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by hectorj-thetreep** [comment] 2023-08-18 15:43
Ideally I would like something like this:

```
type NullableB {
	B B
	Valid bool
}
type GetARow struct {
	A A
	B NullableB
}
```

But it might be tricky to Scan.

An alternative is to have `NullableB` be a copy of `B` with all its fields nullable… not ideal but maybe easier.

**Comment by nickjackson** [comment] 2023-08-18 16:39
this is a duplicate of #2348 and  #2472

**Comment by hectorj-thetreep** [comment] 2023-08-18 17:22
Indeed. Sorry for the noise and thank you.

Le ven. 18 août 2023 à 18:39, Nick Jackson ***@***.***> a
écrit :

**Closed** 2023-08-19 12:09 UTC
Labels: bug, triage
