### ISSUE TITLE
Unable to generate code when using SQLite with LEFT JOIN

### ISSUE THREAD

**Issue by zasdaym** [sqlc-dev/sqlc#1994] opened 2022-12-09 09:03 UTC
### Version

Other

### What happened?

`sqlc generate` failed when using the described schema and query. The version used is v1.16.0.

### Relevant log output

```shell
column reference "id" not found
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS links (
    id TEXT PRIMARY KEY,
    destination TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS visits (
    id TEXT PRIMARY KEY,
    link_id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (link_id) REFERENCES links(id)
);
```

### SQL queries

```sql
-- name: GetLinks :many
SELECT
    links.id,
    links.destination,
    links.created_at,
    links.updated_at,
    COUNT(visits.id) AS visits
FROM links LEFT JOIN visits ON links.id = visits.link_id
GROUP BY links.id;
```

### Configuration

```yaml
version: 2
sql:
  - engine: sqlite
    schema: internal/sqlite/schema.sql
    queries: internal/sqlite/queries.sql
    gen:
      go:
        package: sqlite
        out: internal/sqlite
```

### Playground URL

https://play.sqlc.dev/p/c8d3c10a1bb40e4c91484e3334f3ae33e7764a7f5e4ba6742c6842c4c13c5933

### What operating system are you using?

macOS

### What type of code are you generating?

Go

**Comment by zakaria-chahboun** [comment] 2023-01-07 16:39
+1

**Comment by zakaria-chahboun** [comment] 2023-01-09 10:59
it's worked for me
https://play.sqlc.dev/p/d9035f55cc5e09c0b18e9e798423c4b7e2969b7036ce25d680a553f7d18addf9

**Comment by zakaria-chahboun** [comment] 2023-01-09 11:17
@zasdaym 
Your query is worked now, You just have to work with `placeholders` instead of table names.


```diff
SELECT
- links.id
+    l.id,
-    links.destination,
+    l.destination,
-    COUNT(visits.id) AS visit_count
+    COUNT(v.id) AS visit_count
-FROM links LEFT JOIN visits ON links.id = visits.link_id
+FROM links l LEFT JOIN visits v ON l.id = v.link_id
-GROUP BY links.id;
+GROUP BY l.id;
```
https://play.sqlc.dev/p/253ad0cdf535a53bfe0be3235fa7324d9b10e3b03cfd952bfa57d52404d5dd13

**Comment by zasdaym** [comment] 2023-01-12 11:53
Thanks for the solution @zakaria-chahboun, but the same exact query is working when using the `postgresql` engine.

**Comment by orisano** [comment] 2023-07-11 20:56
Duplicate of #2271, I think.

**Closed** 2023-09-26 09:20 UTC
Labels: bug, :wrench: golang, :computer: darwin, :books: sqlite
