### ISSUE TITLE
`sqlc` generated code as `repository` pattern of clean architecture

### ISSUE THREAD

**Issue by Larleyt** [sqlc-dev/sqlc#2467] opened 2023-07-15 23:17 UTC
As the title states, I'm wondering if it is possible to use `sqlc` generated code as `repository` pattern of clean architecture paradigm?
Are there any examples of such implementation?

Thanks,

**Comment by Jille** [comment] 2023-08-14 19:50
Could you elaborate more on what the repository pattern is? What exactly do you want?

**Comment by Jille** [comment] 2023-08-14 19:51
Is this a duplicate of #2469?

**Comment by kyleconroy** [comment] 2023-10-02 18:13
Duplicate of https://github.com/sqlc-dev/sqlc/issues/2469

**Closed by kyleconroy** 2023-10-02 18:13 UTC
