### ISSUE TITLE
Generate builtin postgresql schema

### ISSUE THREAD

**Issue by Yamakaky** [sqlc-dev/sqlc#1541] opened 2022-04-11 10:01 UTC
### Version

1.12.0

### What happened?

For one of my queries, I use the `pg_catalog.pg_sequence` built-in table, but sqlc says it doesn't exist. My current workaround is to add then delete the following table:
```sqlc
CREATE TABLE if not exists pg_sequence (
  "seqrelid" oid not null,
  "seqmin" bigint not null,
  "seqmax" bigint not null
);
```

### SQL queries

```sql
select * from pg_catalog.pg_sequence;
```

### Playground URL

https://play.sqlc.dev/p/c12d58abd999f7899f83f72411c87786988a24d13cf6452c53513be7f97e32e2

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment] 2023-09-22 20:41
Duplicate of https://github.com/sqlc-dev/sqlc/issues/1171

**Closed by kyleconroy** 2023-09-22 20:41 UTC
Labels: enhancement, :books: postgresql
