### ISSUE TITLE
Embed with table aliases doesn't work when alias mixes cases

### ISSUE THREAD

**Issue by andrei-dascalu** [sqlc-dev/sqlc#2718] opened 2023-09-08 07:26 UTC
### Version

1.21.0

### What happened?

I would have expected the embed to be able to resolve the alias. In the exact same scenario but using all lowercase (eg `locmain` instead of `locMain`) works - sqlc seems to expect lowercase. However, mixing cases is valid SQL so I would say it should be accepted (or if the behavior is desired, it should be documented - however this may make it less readable in certain situations).

### Relevant log output

```shell
query.sql:23:1: unable to resolve table with "sqlc.embed(locmain)": relation "locmain" does not exist
```

### Playground URL

https://play.sqlc.dev/p/8aa8bb4478ca2f7a54533ec2d66a167e580a93f6879ab6af4c5ead6e6b6e989e

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment] 2023-09-13 23:46
Close as a duplicate of https://github.com/sqlc-dev/sqlc/issues/2686

**Closed by kyleconroy** 2023-09-13 23:46 UTC
Labels: bug, triage
