### ISSUE TITLE
Unable to generate struct for record type

### ISSUE THREAD

**Issue by david-alza** [sqlc-dev/sqlc#2420] opened 2023-07-08 19:27 UTC
### Version

1.18.0

### What happened?

I'm attempting to generate some row types from json data in my application. Unfortunately, SQLC seems to bail when trying to generate a struct from these record types. I'm not sure if this is a limitation of the JSON functions or due to limited support in general for records. I didn't see any similar issues with record types, so filing away here. 

With `json_populate_record`: https://play.sqlc.dev/p/79b3c6a6e914e6d22e63cfe5c327fdac124c35be28cd0760f4b867052cb546ec

With `json_to_record`: 
https://play.sqlc.dev/p/bdd5efdf46740ad811a74d219df9272ade54b0ae12421ce89aec4d335a9e6ce9

Issue is that the row struct is empty: 
```
type GetResultRow struct {
}
```

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by david-alza** [comment] 2023-07-08 19:33
I was able to get around this just by casting the selects: 

https://play.sqlc.dev/p/88b89b06f6f4e1f7355e74ddec0f11f73fd69f7113a29e0bd7cd33dce6f873b1

**Comment by kyleconroy** [comment] 2023-09-26 16:51
Duplicate of both https://github.com/sqlc-dev/sqlc/issues/1322 and #2760

**Closed by kyleconroy** 2023-09-26 16:51 UTC
Labels: bug, :books: postgresql, :wrench: golang, analyzer
