### ISSUE TITLE
I need global output_models_file_name

### ISSUE THREAD

**Issue by namndev** [sqlc-dev/sqlc#2247] opened 2023-05-01 06:09 UTC
### What do you want to change?

**Version**
1.18.0
Hi @kyleconroy
I'm glad 1.18 has support for sql.embed and global overrides.

But I need to support adding global output_models_file_name configuration.
scenario: I need to create 2 packages for master and slave. I only need 1 models gen file.

Thanks,

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment] 2023-09-26 16:12
Duplicate of #835 and https://github.com/sqlc-dev/sqlc/issues/1941

**Closed by kyleconroy** 2023-09-26 16:12 UTC
Labels: enhancement, :books: postgresql, :wrench: golang
