### ISSUE TITLE
Unnest into alias doesn't define the column

### ISSUE THREAD

**Issue by Jille** [sqlc-dev/sqlc#1596] opened 2022-05-09 09:37 UTC
### Version

1.12.0

### What happened?

I guess the parser doesn't understand that the alias after UNNEST defines a column, so when later trying to determine the type of the column, it thinks the column doesn't exist.

### Relevant log output

```shell
query.sql:2:8: column "x" does not exist
```

### SQL queries

```sql
-- name: FromUnnest :many
SELECT x FROM UNNEST(array[5,6]) x;
```

### Playground URL

https://play.sqlc.dev/p/01ee6a49034c018482526ca75aa29cf93aa447d3d93417543266cd4a6d1577b0

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by Jille** [comment] 2022-05-09 09:49
```
$ SQLCDEBUG=dumpast=1 sqlc generate
([]interface {}) (len=1 cap=1) {
 (*ast.RawStmt)(0xc00052cb60)({
  Stmt: (*ast.SelectStmt)(0xc0003f1e40)({
   DistinctClause: (*ast.List)(0xc000642570)({
    Items: ([]ast.Node) <nil>
   }),
   IntoClause: (*ast.IntoClause)(<nil>),
   TargetList: (*ast.List)(0xc000642588)({
    Items: ([]ast.Node) (len=1 cap=1) {
     (*ast.ResTarget)(0xc00063f3e0)({
      Name: (*string)(<nil>),
      Indirection: (*ast.List)(0xc0006425a0)({
       Items: ([]ast.Node) <nil>
      }),
      Val: (*ast.ColumnRef)(0xc00052cae0)({
       Name: (string) "",
       Fields: (*ast.List)(0xc0006425b8)({
        Items: ([]ast.Node) (len=1 cap=1) {
         (*ast.String)(0xc0006445a0)({
          Str: (string) (len=1) "x"
         })
        }
       }),
       Location: (int) 33
      }),
      Location: (int) 33
     })
    }
   }),
   FromClause: (*ast.List)(0xc0006425d0)({
    Items: ([]ast.Node) (len=1 cap=1) {
     (*ast.RangeFunction)(0xc00052cb40)({
      Lateral: (bool) false,
      Ordinality: (bool) false,
      IsRowsfrom: (bool) false,
      Functions: (*ast.List)(0xc0006425e8)({
       Items: ([]ast.Node) (len=1 cap=1) {
        (*ast.List)(0xc000642600)({
         Items: ([]ast.Node) (len=2 cap=2) {
          (*ast.FuncCall)(0xc00063b950)({
           Func: (*ast.FuncName)(0xc00063f440)({
            Catalog: (string) "",
            Schema: (string) "",
            Name: (string) (len=6) "unnest"
           }),
           Funcname: (*ast.List)(0xc000642618)({
            Items: ([]ast.Node) (len=1 cap=1) {
             (*ast.String)(0xc0006445e0)({
              Str: (string) (len=6) "unnest"
             })
            }
           }),
           Args: (*ast.List)(0xc000642630)({
            Items: ([]ast.Node) (len=1 cap=1) {
             (*ast.A_ArrayExpr)(0xc000644610)({
              Elements: (*ast.List)(0xc000642648)({
               Items: ([]ast.Node) (len=2 cap=2) {
                (*ast.A_Const)(0xc000642660)({
                 Val: (*ast.Integer)(0xc000648090)({
                  Ival: (int64) 5
                 }),
                 Location: (int) 53
                }),
                (*ast.A_Const)(0xc000642678)({
                 Val: (*ast.Integer)(0xc000648098)({
                  Ival: (int64) 6
                 }),
                 Location: (int) 55
                })
               }
              }),
              Location: (int) 47
             })
            }
           }),
           AggOrder: (*ast.List)(0xc000642690)({
            Items: ([]ast.Node) <nil>
           }),
           AggFilter: (*ast.TODO)(0x2114930)({
           }),
           AggWithinGroup: (bool) false,
           AggStar: (bool) false,
           AggDistinct: (bool) false,
           FuncVariadic: (bool) false,
           Over: (*ast.WindowDef)(<nil>),
           Location: (int) 40
          }),
          (*ast.TODO)(0x2114930)({
          })
         }
        })
       }
      }),
      Alias: (*ast.Alias)(0xc000644660)({
       Aliasname: (*string)(0xc000644650)((len=1) "x"),
       Colnames: (*ast.List)(0xc0006426a8)({
        Items: ([]ast.Node) <nil>
       })
      }),
      Coldeflist: (*ast.List)(0xc0006426c0)({
       Items: ([]ast.Node) <nil>
      })
     })
    }
   }),
   WhereClause: (*ast.TODO)(0x2114930)({
   }),
   GroupClause: (*ast.List)(0xc0006426d8)({
    Items: ([]ast.Node) <nil>
   }),
   HavingClause: (*ast.TODO)(0x2114930)({
   }),
   WindowClause: (*ast.List)(0xc0006426f0)({
    Items: ([]ast.Node) <nil>
   }),
   ValuesLists: (*ast.List)(0xc000642708)({
    Items: ([]ast.Node) <nil>
   }),
   SortClause: (*ast.List)(0xc000642720)({
    Items: ([]ast.Node) <nil>
   }),
   LimitOffset: (*ast.TODO)(0x2114930)({
   }),
   LimitCount: (*ast.TODO)(0x2114930)({
   }),
   LockingClause: (*ast.List)(0xc000642738)({
    Items: ([]ast.Node) <nil>
   }),
   WithClause: (*ast.WithClause)(<nil>),
   Op: (ast.SetOperation) None,
   All: (bool) false,
   Larg: (*ast.SelectStmt)(<nil>),
   Rarg: (*ast.SelectStmt)(<nil>)
  }),
  StmtLocation: (int) 0,
  StmtLen: (int) 60
 })
}
```

**Comment by kyleconroy** [comment] 2022-06-04 15:36
> I guess the parser doesn't understand that the alias after UNNEST defines a column

That is indeed the case.

**Comment by ryan-berger** [comment] 2022-06-21 17:59
I had another idea right after I hit send. 

The other option we have is to use a rewrite pass for these aliases since `ast.Alias` is a `sqlc` owned type.

During a rewrite we can pattern match the `*pg_ast.List{*pg_ast.FunctionCall, *pg_ast.Alias}` and transform it to something along the lines of: `*ast.List{*ast.Alias{Node: *ast.FunctionCall}}`.

This would require updating the `*ast.Alias` type to have new fields, but should theoretically be backwards compatible, and I believe that since it is in `internal/` it shouldn't be breaking for any outward facing APIs

**Comment by pyc92** [comment] 2022-12-21 08:54
any workaround for this issue?

**Comment by kyleconroy** [comment] 2023-09-26 08:34
Closing as a duplicate of https://github.com/sqlc-dev/sqlc/issues/1322

**Closed by kyleconroy** 2023-09-26 08:34 UTC
Labels: bug, :books: postgresql, :wrench: golang, :computer: linux
