### ISSUE TITLE
request feature to support returning table of multiple fields

### ISSUE THREAD

**Issue by brlala** [sqlc-dev/sqlc#1898] opened 2022-10-15 09:30 UTC
### What do you want to change?

is it possible to add support for multifields table return?

Currently this returns the correct int type
```
CREATE FUNCTION table_args(x INT) RETURNS TABLE (y INT) AS 'SELECT x' LANGUAGE sql;

-- name: TableArgs :one
SELECT table_args(x => $1);

func (q *Queries) TableArgs(ctx context.Context, x int32) (int32, error) {
	row := q.db.QueryRow(ctx, tableArgs, x)
	var table_args interface{}
	err := row.Scan(&table_args)
	return table_args, err
}
```

adding a 2nd parameter to the table, this will return an interface{} type
```
CREATE FUNCTION table_args(x INT) RETURNS TABLE (y INT, a INT) AS 'SELECT x' LANGUAGE sql;

-- name: TableArgs :one
SELECT table_args(x => $1);

func (q *Queries) TableArgs(ctx context.Context, x int32) (interface{}, error) {
	row := q.db.QueryRow(ctx, tableArgs, x)
	var table_args interface{}
	err := row.Scan(&table_args)
	return table_args, err
}
```

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment] 2023-09-26 09:11
Duplicate of https://github.com/sqlc-dev/sqlc/issues/1322

**Closed by kyleconroy** 2023-09-26 09:11 UTC
Labels: enhancement, :books: postgresql, :wrench: golang
