### ISSUE TITLE
sqlc.embed() AS alias does not work

### ISSUE THREAD

**Issue by kevinvalk** [sqlc-dev/sqlc#2655] opened 2023-08-24 20:07 UTC
### Version

1.20.0

### What happened?

The alias is not used when using `sqlc.embed(name) AS alias`.
https://github.com/sqlc-dev/sqlc/blob/8c59fbb9938a0bad3d9971fc2c10ea1f83cc1d0b/internal/compiler/output_columns.go#L262-L270

I think it would make sense to keep this information available somehow as now it is impossible to name sqlc.embed when using for example joins or views.

**Comment by orisano** [comment] 2023-08-24 23:27
@andrewmbenton Should I work on this issue?

**Comment by kevinvalk** [comment] 2023-08-27 20:35
Small detail, you can use aliases inside the sqlc.embed. So you can do a `SELECT sqlc.embed(t) FROM other_table LEFT JOIN some_table AS t ON ...`. That said, if you have a typo or did not name the embed correctly you immediately get an ` edited query syntax is invalid: syntax error at or near ","` error, this is definitely not the nicest error to throw to an end user.

**Comment by kyleconroy** [comment] 2023-09-13 23:44
Close as duplicate of https://github.com/sqlc-dev/sqlc/issues/2686

**Closed by kyleconroy** 2023-09-13 23:44 UTC
Labels: bug, triage
