### ISSUE TITLE
Support the PostgreSQL engine on Windows

### ISSUE THREAD

**Issue by dharmjit** [sqlc-dev/sqlc#282] opened 2020-01-20 12:33 UTC
Hi, I just started exploring this project. But not able to build the project on windows. Is windows support in the road map. Thanks

**Comment by euller88** [comment] 2020-01-20 12:59
Can you specify the error message?

**Comment by dharmjit** [comment] 2020-01-20 13:07
I am getting below error.
```
github.com\lfittl\pg_query_go@v1.0.0\parser\include/port.h:17:19: fatal error: netdb.h: No such file or directory                                                                                                                                  compilation terminated.
```

**Comment by euller88** [comment] 2020-01-20 13:27
Ah, the dreaded "missing C header files" error. First, this seems like a problem within pg_query_go and the C header files available on your system. I have two recommendations for you:

1. if you are in Windows 10, activate WSL2, and use sqlc within the Linux subsystem. Be sure to install gcc on it.
2. Try the vendoring instructions present in the [pg_query_go repo](https://github.com/lfittl/pg_query_go#usage-with-go-modules), and see if it works.

I will research a little bit more in order to see if there is some other options, but those two are the ones that were on the top of my mind.

**Comment by landbed** [comment] 2020-03-13 09:35
@kyleconroy @euller88 how about providing a binary file on every releases? user can download directly?

**Comment by kyleconroy** [comment] 2020-03-13 21:46
@landbed that is already the case. You can download macOS and Linux binaries for every commit on [master](https://github.com/kyleconroy/sqlc#tip-releases). Each [release](https://github.com/kyleconroy/sqlc/releases/tag/v1.0.0) also has binaries.

The issue is that out PostgreSQL parser [does not support Windows](https://godoc.org/github.com/lfittl/pg_query_go). Once MySQL support is complete, we'll offer a Windows version that does not support PostgreSQL.

**Comment by dharmjit** [comment] 2020-03-14 10:00
Hi @kyleconroy, windows binaries then will not be useful for people using postgresql.

**Comment by 766b** [comment] 2020-06-19 22:02
Just FYI, you can run `sqlc` on Windows by installing [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) then using compiled Linux binary. Probably can add this to readme as temporary workaround for Windows users.

**Comment by kyleconroy** [comment] 2021-02-08 16:47
Initial Windows support is now live (#886). 

```bash
GOOS=windows GOARCH=amd64 go build ./cmd/sqlc/
```

These builds have a huge limitation: the PostgreSQL engine does not work. While that's obviously not ideal, it's good for those people that only need MySQL support.

**Comment by arif2009** [comment] 2022-02-17 14:40
> Just FYI, you can run `sqlc` on Windows by installing [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) then using compiled Linux binary. Probably can add this to readme as temporary work around for Windows users.

It's not working on WSL as well. This is my try:
![2022-02-17_20h38_07](https://user-images.githubusercontent.com/6396346/154504562-913a4700-4fed-4d70-8586-903d86e237c7.png)

**Comment by bmerracho** [comment] 2022-03-20 17:59
Hello any updates regarding this issue? is there a possibility for postgresql support in windows soon?

**Comment by pawlobanano** [comment] 2022-04-06 21:34
> > Just FYI, you can run `sqlc` on Windows by installing [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) then using compiled Linux binary. Probably can add this to readme as temporary work around for Windows users.
> 
> It's not working on WSL as well. This is my try:

Fortunately it is working. There is a little hack for the lack of systemd in wsl2, but it is surmountable via commands mentioned here: https://github.com/microsoft/WSL/issues/5126#issuecomment-653715201
and then simple install: `sudo snap install sqlc`

**Comment by gafful** [comment] 2022-08-25 14:15
I ended up installing sqlc with homebrew on WSL

**Comment by NinoM4ster** [comment] 2023-01-02 02:45
I'm sorry for being rude but how is this **3 years in** and still not fixed?!

I've just started migrating a new project from GORM and this is honestly unacceptable.

The WSL workaround is not enough, I think the parser should have native Windows support.

**Comment by eullerpereira94** [comment] 2023-01-03 12:51
@NinoM4ster the parser is a different project that is not maintained by Kyle. You can always open an issue on the pg_query_go repository. Also, any contributions towards a parser that works on Windows would be greatly appreciated.

**Comment by NinoM4ster** [comment] 2023-01-03 23:24
> You can always open an issue on the pg_query_go repository.


[This issue](https://github.com/pganalyze/pg_query_go/issues/25) seems to track that already. Thanks.

**Comment by GustavoCielo** [comment] 2023-01-05 12:18
Oh wow, tried the WSL workaround, but still didnt work, damn

**Comment by malcolmmaima** [comment] 2023-01-23 09:30
> sqlc generate 

Gives:

C:\Users\Malcom\Github\....\db\migration\000001_init_schema.up.sql:1:1: the PostgreSQL engine does not support Windows

Guess it's time to get a Mac, this sucks!

**Comment by mulukenhailu** [comment] 2023-07-04 21:56
> > sqlc generate
> 
> Gives:
> 
> > C:\Users\Malcom\Github....\db\migration\000001_init_schema.up.sql:1:1: the PostgreSQL engine does not support Windows
> 
> Possible solution in windows (worked for me):
> 
> > docker run --rm -v "%cd%:/src" -w /src kjconroy/sqlc generate

please, can you explain  step by step how it worked for you on Windows?

**Comment by kokodayou2000** [comment] 2023-07-05 08:44
> > > sqlc generate
> > 
> > 
> > Gives:
> > > C:\Users\Malcom\Github....\db\migration\000001_init_schema.up.sql:1:1: the PostgreSQL engine does not support Windows
> > 
> > 
> > Possible solution in windows (worked for me):
> > > docker run --rm -v "%cd%:/src" -w /src kjconroy/sqlc generate
> 
> please, can you explain step by step how it worked for you on Windows?



> > > sqlc generate
> > 
> > 
> > Gives:
> > > C:\Users\Malcom\Github....\db\migration\000001_init_schema.up.sql:1:1: the PostgreSQL engine does not support Windows
> > 
> > 
> > Possible solution in windows (worked for me):
> > > docker run --rm -v "%cd%:/src" -w /src kjconroy/sqlc generate
> 
> please, can you explain step by step how it worked for you on Windows?

I just ran into this issue as well

first use `pwd` command
get path
C:\Users\03062\Desktop\Code\workspace\project\golang\simplebank
second 
copy the path 
docker run --rm -v "C:\Users\03062\Desktop\Code\workspace\project\golang\simplebank:/src" -w /src kjconroy/sqlc generate

https://docs.sqlc.dev/en/latest/overview/install.html#docker

**Comment by robinmuhia** [comment] 2023-07-05 09:45
Just run that command exactly as it is... do not change anything

**Comment by Tesohh** [comment] 2023-08-02 09:58
> > Just FYI, you can run `sqlc` on Windows by installing [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) then using compiled Linux binary. Probably can add this to readme as temporary work around for Windows users.
> 
> 
> 
> It's not working on WSL as well. This is my try:
> 
> ![2022-02-17_20h38_07](https://user-images.githubusercontent.com/6396346/154504562-913a4700-4fed-4d70-8586-903d86e237c7.png)
> 
> 
> 
> 

try (in wsl): `~/go/bin/sqlc generate`

**Comment by andrewmbenton** [comment] 2023-08-30 06:58
There is an option to use `sqlc` with remote codegen execution, which is perhaps a suitable workaround for Windows PostgreSQL users: https://docs.sqlc.dev/en/stable/reference/changelog.html#remote-code-generation

Otherwise the best solution seems to be using a downloaded release binary with WSL.

I am closing this issue since `pg_query_go` likely won't be updated to support Windows, and the above workarounds are stable.

**Closed by andrewmbenton** 2023-08-30 06:58 UTC
Labels: :books: postgresql, upstream

**Comment by Ali-Adel-Nour** [comment] 2023-10-15 08:04
version: "2"
packages:
  - name: "db"
    path: "./db/sqlc"
    queries: "./db/query/"
    schema: "./db/migration/"
    engine: "postgresql"
    emit_json_tags: true
    emit_prepared_queries: false
    emit_interface: false
    emit_exact_table_names: false

I keep getting this error
error parsing sqlc.yaml: yaml: unmarshal errors:
  line 2: field packages not found in type config.Config
make: *** [Makefile:14: sqlc] Error 1

**Comment by andrewmbenton** [comment] 2023-10-15 14:13
@Ali-Adel-Nour Your config structure looks like version "1" but you've specified version "2". Your config should parse if you set `version: "1"`.

**Comment by bontusss** [comment] 2023-11-24 10:14
I decided to use the wsl workaround but it didn't see my database. I've installed postgres on wsl but there's no way to access it on pgadmin.
