### ISSUE TITLE
Deduplicate generated structs

### ISSUE THREAD

**Issue by loicbefve** [sqlc-dev/sqlc#2607] opened 2023-08-12 16:22 UTC
### What do you want to change?

Let's consider those two SQL queries :

**Query 1:**
```sql
-- name: get_members :many
SELECT * FROM members; 
```

**Query 2:**
```sql
-- name: get_connected_members :many
SELECT * FROM members WHERE status = 'connected';
```

In both cases I get a `MemberRow` but sqlc will generate two different models `GetMembersRow` and `GetConnectedMembersRow` that will be identical.

It would be great that istdetects that they are the same and then generate a unique `MemberRow`.

### What database engines need to be changed?

PostgreSQL, MySQL, SQLite

### What programming language backends need to be changed?

Go, Python, Kotlin

**Comment by loicbefve** [comment] 2023-08-12 16:35
It could only works on query mapping exactly to a table to avoid naming problems and the name of the model could be the name of the table. In our example `Member`

**Comment by andrewmbenton** [comment] 2023-08-14 16:59
I think I understand what you're asking, but the specific example you've cited actually does the thing you want (for `SELECT * ...`). Here's a playground URL: https://play.sqlc.dev/p/dc32f36841126622fe128376a72ec1b084582d43762a06ddb0cd92f0d121716f

I am assuming there's an example where two different row structs are generated, so can you share that?

**Comment by hezise** [comment] 2023-08-15 16:06
I'd like to join this.
my example is more complexed, but the idea is the same.
the requested fields for the two different queries are the same 
but the row struct is different

**Comment by kyleconroy** [comment] 2023-10-02 20:13
Duplicate of https://github.com/sqlc-dev/sqlc/issues/781

**Closed by kyleconroy** 2023-10-02 20:13 UTC
Labels: enhancement, triage
