### ISSUE TITLE
add arch linux/amd64 to Docker image sqlc/sqlc

### ISSUE THREAD

**Issue by zcubbs** [sqlc-dev/sqlc#2659] opened 2023-08-26 12:38 UTC
### Version

1.20.0

### What happened?

Since version [1.8.0](https://hub.docker.com/layers/sqlc/sqlc/1.8.0/images/sha256-da503b3cead5d35ba83549b2a0ed85a2da56130876adbaad9f3e5da3e3650093?context=explore) in docker hub the image is only pushed for linux/arm64, is it possible to add amd64 as before.
Thank you.

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment] 2023-08-29 16:48
Duplicate of https://github.com/sqlc-dev/sqlc/issues/2609

**Closed** 2023-08-30 18:47 UTC
Labels: bug, triage
