### ISSUE TITLE
consistent field naming for _id columns

### ISSUE THREAD

**Issue by bassettb** [sqlc-dev/sqlc#3306] opened 2024-04-01 13:43 UTC
### What do you want to change?

Column names ending in "_id" are handled inconsistently when converting to Go field names.  For example, `app_id` becomes `AppID` instead of `AppId`.  It would be a breaking change to fix this for all users.  

I propose creating a new config option, `use_capital_id`, that enables a more consistent naming scheme with no special handling for `_id` columns.  IE, they become Go fields ending in `Id` .  

This may seem nit-picky.  But migrating a large existing application to sqlc is challenging.  If the developers were consistent in naming Id columns (of which there are many), then it becomes much harder to drop in new sqlc generated objects.  This change would save developers having to add a hundreds of rename rules.
  

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment] 2024-04-01 15:39
Thanks for the feature request. Instead of a specific setting for id, I think the solution proposed at the bottom of #2161 is the best, giving you the ability to configure with words are all caps.

Closing as a duplicate of https://github.com/sqlc-dev/sqlc/issues/2161

**Closed by kyleconroy** 2024-04-01 15:39 UTC
Labels: enhancement

**Comment by kyleconroy** [comment] 2024-04-01 19:21
Fixed in https://github.com/sqlc-dev/sqlc/pull/3308
