### ISSUE TITLE
Suggesting db_type -> db_types (Array) to have a pretty config file 

### ISSUE THREAD

**Issue by hariprasadrajaram** [sqlc-dev/sqlc#1292] opened 2021-11-19 07:31 UTC
Hi, Sql.NullString with json tags serves no purpose when you can't marshal and unmarshal it in the right way. 

I would suggest to bring up an approach like this within **sqlc** to avoid such a problem 
https://github.com/soarcn/GoJsonSqlNullObj/blob/master/nullobj.go

**Comment by podhmo** [comment] 2021-11-27 07:17
Hello, I also had a similar problem. And this is my work-around.

1. use https://github.com/guregu/null
2. override type settings

the settings is something like this.

sqlc.yaml

```yaml
version: 1
packages:
- path: tutorial
  name: tutorial
  engine: postgresql
  schema: schema.sql
  queries: query.sql
  emit_json_tags: true
  emit_db_tags: true
  overrides:
  - go_type:
      import: gopkg.in/guregu/null.v4
      package: 'null'
      type: String
    db_type: text
    nullable: true
```

**Comment by hariprasadrajaram** [comment] 2021-11-30 14:41
Yeah. It is known implication, but can be reduced by integrating it in sqlc itself ,rather than going for a heavy configuration. look at my configuration. 


Also, check this out 
for NullInt32, I have to repeat the same thing for different database types, It is quite heavy. 

`yaml
version: "2"
sql:
  - schema: "persistence/gen/users/schema.sql"
    queries: "persistence/gen/users/queries.sql"
    engine: "postgresql"
    gen:
      go:
        package: "users"
        out: "persistence/gen/users"
        emit_interface: true
        emit_json_tags: true
        emit_prepared_queries: true
        emit_empty_slices: true
        emit_db_tags: true
        emit_exported_queries: true
        json_tags_case_style: camel
overrides:
  go:
    overrides:
      - go_type:
          import: <project>
          package: database
          type: NullInt32
          pointer: false
        db_type: pg_catalog.serial4
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullInt32
          pointer: false
        db_type: serial4
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullInt64
          pointer: false
        db_type: pg_catalog.serial8
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullInt64
          pointer: false
        db_type: bigserial
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullInt32
          pointer: false
        db_type: pg_catalog.int4
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullInt32
          pointer: false
        db_type: int4
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullInt32
          pointer: false
        db_type: integer
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullInt32
          pointer: false
        db_type: int
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullInt64
          pointer: false
        db_type: pg_catalog.int8
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullInt64
          pointer: false
        db_type: int32
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullFloat64
          pointer: false
        db_type: pg_catalog.float8
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullFloat64
          pointer: false
        db_type: float8
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullFloat64
          pointer: false
        db_type: pg_catalog.float4
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullString
          pointer: false
        db_type: pg_catalog.numeric
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullBool
          pointer: false
        db_type: pg_catalog.bool
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullTime
          pointer: false
        db_type: pg_catalog.timestamp
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullTime
          pointer: false
        db_type: pg_catalog.timestamptz
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullTime
          pointer: false
        db_type: timestamptz
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullTime
          pointer: false
        db_type: pg_catalog.time
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullTime
          pointer: false
        db_type: pg_catalog.timetz
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullTime
          pointer: false
        db_type: date
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullString
          pointer: false
        db_type: pg_catalog.varchar
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullString
          pointer: false
        db_type: text
        engine: postgresql
        nullable: true

      - go_type:
          import: <project>
          package: database
          type: NullString
          pointer: false
        db_type: string
        engine: postgresql
        nullable: true
`

**Comment by hariprasadrajaram** [comment] 2021-12-06 10:51
I would suggest something like `db_types` as an array instead of `db_type`
```yaml
 - go_type:
          import: <project>
          package: database
          type: NullString
          pointer: false
        db_types:
          -  string
          -  text
          - pg_catalog.varchar
        engine: postgresql
        nullable: true
```

**Comment by hariprasadrajaram** [comment] 2022-02-22 03:07
@kyleconroy what is your feedback on this?

**Comment by kyleconroy** [comment] 2023-09-26 16:54
Duplicate of https://github.com/sqlc-dev/sqlc/issues/1292

**Comment by kyleconroy** [comment] 2023-09-26 16:54
Duplicate of https://github.com/sqlc-dev/sqlc/issues/1606

**Closed by kyleconroy** 2023-09-26 16:54 UTC
Labels: enhancement
